name: harry_potter
description: Harry Potter for Lego demo
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  i69n: ^3.1.0
  injectable: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  injectable_generator: ^2.7.0